import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import Providers from "./providers";
// @ts-ignore: allow importing CSS without type declarations
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
